# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52f5e79fe7e0a15f49762aba05145109a73426f742a9df115f19a73a85219652922e1eee77b0cbabafd194341669e32529457f433fba80912e17b9f9aa20d083

test:
  secret_key_base: 2da4141d17b773ef0d8501a2a7e86ba97af08cef0efd81c0a828e90d8a911895482961c3b58ce5573aeb968a4a15d92db2b18fc409ce673348b9bb35e5689c83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
